name: CI-CD-Pipeline-to-Heroku

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repository
      uses: actions/checkout@v2
      
    - name: Install Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      
    - name: Test my application using unittest
      run: python3 -m unittest tests.py
       
    - name: Login to docker hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Create docker image from Dockerfile
      run : docker build -t lombard-app-${{ github.sha }}:ver-${{ github.sha }} .
      
        
    - name: Push my docker image to docker hub
      run : | 
              docker tag lombard-app-${{ github.sha }}:ver-${{ github.sha }} jtwist/lombard-app:ver-${{ github.sha }}
              docker push jtwist/lombard-app:ver-${{ github.sha }}
       

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0
       
       
     - name: Configure my Heroku credentials
       run: |
            cat > ~/.netrc <<EOF
              machine api.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API_KEY
              machine git.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API_KEY
            EOF
       env:
           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
           HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    
    
     - name: Add Heroku remote
       run: heroku git:remote --app $HEROKU_APP_NAME
       env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          
          
     - name: Deploy to Heroku
       run: git push heroku master
